import type { Metadata } from 'next'
import { Tiro_Gurmukhi } from 'next/font/google'
import './globals.css'

// Call the font loader and assign it to a constant in the module scope
const tiroGurmukhiFontLoader = Tiro_Gurmukhi({ weights: [400], subsets: ['latin-ext'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-[#8c9192] text-slate-200'>
      <body className={`font-${tiroGurmukhiFontLoader}`}>{children}</body>
    </html>
  )
}
