// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  educationn: dynamic(() => import("./Educationn")),
  experience: dynamic(() => import("./Experience")),
  fields_list: dynamic(() => import("./FieldsList")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  text_block: dynamic(() => import("./TextBlock")),
};
