// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  educationn: dynamic(() => import("./Educationn")),
  fields_list: dynamic(() => import("./FieldsList")),
  hero: dynamic(() => import("./Hero")),
  text_block: dynamic(() => import("./TextBlock")),
};
